export const negative = [
  '🤗🤗🤗',
  'How can I help?',
  'Is there something I can do for you?',
  'I believe in you… You’re awesome!',
  'I’m here if you want to talk.',
  'You’re not alone in this',
  'Hey, you’re not crazy!',
  "You're not alone in feeling like this",
  'Just do the best you can',
  "It's okay to not be okay",
  'Good things take time',
  'Keep going',
  'You are stronger than you know',
  "Don't stop until you're proud",
  'You can do it',
  'Love what you do',
  'You are amazing',
  "Tough times don't last",
];
